### ISSUE TITLE
AzureDevops Deploy Intergration

### ISSUE THREAD

**Issue by Mikael159** [Azure/Industrial-IoT#1090]
Hello,

I would like to integrate the Azure Industrial iot deployment into a devops chain.
We are currently using AzureDevops for our Deployment Pipeline.

How do I add the deployment to my devops chain?

I tried with the statement "deploy.cmd -type minimum -version 2.7.182 [...]" but it got stuck at the "Signing in ..." step.

Do you have a way to do it?

step to reproduce :

```
- checkout: git://# Azure Repos Git repository / clone of AzureIndustrialIot
  displayName: 'AIIoT Checkout Industrial-IoT'
- task: AzurePowerShell@4
  displayName: 'AIIoT Azure CLI Script Test'
  inputs:
    azureSubscription: ${{ parameters.TargetSubscriptionConnection }}
    scriptType: inlineScript
    azurePowerShellVersion: 5.3.0
    inline: |
     $(Agent.BuildDirectory)\s\deploy.cmd -type minimum -version 2.7.182  [...]
```

thank you, 
best regards
