### ISSUE TITLE
Publish to unified namespace using UseBrowseNames..not working

### ISSUE THREAD

**Issue by RollsChris** [Azure/Industrial-IoT#2225]
**Describe the bug**
When setting the publisher to use MQTT and trying to publish to a unified namespace. UsBrowseNames does not work as expected 

**To Reproduce**
Set the publisher to the following:

```yaml
  publisher:
    command: --autoaccept --trustowncert --diagnosticsinterval=60 --publishfile=/publishervolume/publishednodes.json
      --createifnotexist --strict --messageencoding=Json --qos=AtLeastOnce --messagetimestamp=CurrentTimeUtc
      --sendkeepalives --defaultmessagetransport=Mqtt
    container_name: publisher
    environment:
    - EdgeModuleCACertificateFile=/mnt/edgemodule/edge-device-ca.cert.pem
     extra_hosts:
    - opctestsvr:192.168.178.26
    hostname: publisher
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    labels:
      iotedgehubdev: ''
    networks:
      azure-iot-edge-dev: null
    restart: always
    volumes:
    - source: publishervolume
      target: /publishervolume
      type: volume
    - source: edgemoduledev
      target: /mnt/edgemodule
      type: volume
```
Publisher override
```yaml
publisher:
    environment:
      MqttClientConnectionString: "HostName=mosquitto;Port=1883;UseTls=false;Protocol=v5"
      DefaultDataSetRouting: "UseBrowseNames"
      MessagingMode: "PubSub"
      PublisherId: GatewayPublisherModule
      SiteId: England
    depends_on:
      - mosquitto
```

But im not seeing anything that resembles the address space, the topics are created using the default pattern: 
**{RootTopic}/messages/{WriterGroup}**

**Expected behavior**
If my understanding is correct i should be seeing topics matching the folder heierarchy: 
![image](https://github.com/Azure/Industrial-IoT/assets/6059035/177ccab8-3740-4d42-a186-fd108a9c8ab8)

**Screenshots**

**Desktop (please complete the following information):**
Using the iotedgedev container
