### ISSUE TITLE
Support for Mapping Connection Endpoints or OpcNodes to IoT Edge Message Outputs via Configuration

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/Industrial-IoT#2359]
**Description:**
I would like to request a feature that allows users to configure a mapping between OPC UA connection endpoints or specific OpcNodes and IoT Edge message outputs. This would enable the creation of different edge transformations based on the connectivity definition, allowing more granular control over the message flows and processing logic.

**Motivation:**
In many use cases, there is a need to apply different transformations or processing to data coming from distinct OPC UA connection endpoints or specific OpcNodes. Currently, the publisher lacks the capability to easily route data from different sources to separate message outputs, which restricts flexibility in edge processing.

By enabling configurable mapping between connection endpoints or OpcNodes and IoT Edge message outputs, users can create distinct processing pipelines for different data sources. This will enhance the OPC UA Publisher’s ability to handle complex IoT Edge deployments where data from various OPC UA sources needs to be processed differently.

**Proposed Solution:**
Add support in the configuration file for specifying which OPC UA connection endpoints or OpcNodes should be mapped to particular IoT Edge message outputs. This mapping would allow the following:

Connection Endpoint to Message Output: Route data from specific OPC UA connection endpoints to different message outputs.
OpcNodes to Message Output: Route data from individual or grouped OpcNodes to specific message outputs.

```yaml
connectionEndpoints:
  - endpoint: "opc.tcp://endpoint1:4840"
    messageOutput: "output1"
    opcNodes:
      - nodeId: "ns=2;s=Sensor1"
        messageOutput: "output1"
      - nodeId: "ns=2;s=Sensor2"
        messageOutput: "output2"
  - endpoint: "opc.tcp://endpoint2:4840"
    messageOutput: "output2"
```
